### ISSUE TITLE
Support for shrinkpdf under Windows

### ISSUE THREAD

**Issue by gerking** [gi-ev/LNI-proceedings#10]
Shrinking the final proceedings.pdf seems not to be supported under Windows. 

1. Maybe there should be an explizit hin to run the script through the Git bash?
2. `mgs` must be called instead of `gs` (using MikTeX)
3. The `PDFSETTINGS` and `AutoRotatePages` options require a double slash instead of a single slash
4. The resulting PDF is optimized for printing, so all hyperlinks are removed. Shouldn't it be called using the `dPrinted=false` option to preserve the links?

For me the following invocation succeeded: 

`shrink ()`
`{`
`	mgs					\`
`	  -q -dNOPAUSE -dBATCH -dSAFER		\`
`	  -sDEVICE=pdfwrite			\`
`	  -dCompatibilityLevel=1.4		\`
`	  -dPDFSETTINGS=//printer		\`
`	  -dPrinted=false				\`
`	  -dEmbedAllFonts=true			\`
`	  -dSubsetFonts=true			\`
`	  -dCompressFonts=true			\`
`	  -dFastWebView=true			\`
`	  -dAutoRotatePages=//None		\`
`	  -dDetectDuplicateImages=true		\`
`	  -sOutputFile="$2"			\`
`	  "$1"`
`}`

**Comment by koppor** [comment]
Reading https://tex.stackexchange.com/a/58393/9075, I am not sure whether `//None` is really correct. Need to double check.

I added `-Printed=false`.
