### ISSUE TITLE
Port `metaExtract.py` to Python 3

### ISSUE THREAD

**Issue by koppor** [gi-ev/LNI-proceedings#14]
When modernizing this, I also updated to Python3. This was not that easy.

Seems that I broke `metaExtract.py` at my naive update at https://github.com/gi-ev/LNI-proceedings/pull/13.

@heseba May I ask whether you have Python3 skills and could properly update `metaExtract.py` to Python3? (Or should I try to get python2 running ^^)

**Comment by heseba** [comment]
@koppor Yes, I should be able to do that. How urgent/time-critical is this, as I am currently quite busy?

**Comment by koppor** [comment]
@heseba Seeing https://fg-tav.gi.de/mitteilung/cfp-workshop-jahrestagung-2021, I would ask for 30.06.2021 to ensure that the proceedings of Informatik 2021 can be typeset with this repository.

**Comment by heseba** [comment]
Ok, I have updated the script to work with python 3 in pull request #15

**Comment by koppor** [comment]
@heseba Thank you for working on this! - First check: looks good to me! Let's see, what the users will say.
