### ISSUE TITLE
Add script for processing publisher's PDF

### ISSUE THREAD

**Issue by koppor** [gi-ev/LNI-proceedings#6]
The links in the PDF by the publisher are broken. There needs to be a script taking the publishers PDF and replacing the content by the proceedings PDF (and keeping the cover pages).

(If I understood @ibogicevic correctly)

**Comment by ibogicevic** [comment]
Yes, that's correct. The links got broken in the last finalization step that was done by the publisher (at least for the proceedings of the SE/SWM 2019). An alternative solution would be to ask the publisher whether he could edit the pages in a way so that the links stay the same.

**Comment by gerking** [comment]
In my case the links were **not** broken in the PDF file received from the publisher. 
Maybe they improved their internal process? If so, a script to process that file is no longer required.

**Comment by koppor** [comment]
@gerking Nice. As soon as it is available at GI, could you file a PR to add it to https://github.com/gi-ev/LNI-proceedings/blob/master/README.md#success-stories?
