### ISSUE TITLE
Replacement of textunderscore in bibliography file does not take effect

### ISSUE THREAD

**Issue by gerking** [gi-ev/LNI-proceedings#9]
make-proceedings replaces \textunderscore inside the proceedings.bib file. This doesn't seem to take effect, at least not in make-proceedings.bat under Windows:

`sed -i "s/\\\\textunderscore //g" proceedings.bib`

First, the above command seems to remove \textunderscore instead of replacing it with the _ character.
Second, why are there four backslashes in total? In my case the replacement worked only with two backslashes (one additional backslah to escape the given backslash of \textunderscore).

**Comment by koppor** [comment]
Although, I don't understand, why it works, I cannot reproduce the issue with `\\\\`. I even tried the single quote.

```
koppor@DESKTOP-KAK953S c:\git-repositories\gi\LNI-proceedings
$ sed -i 's/\\textunderscore /_/g' proceedings.bib

koppor@DESKTOP-KAK953S c:\git-repositories\gi\LNI-proceedings
$ cat proceedings.bib
@inproceedings{A1-1,
 author = {Vorname Nachname},
 title = {Erster eingeladener Vortrag},
 booktitle = {Conference Name (CN 2017)},
 pages = {13--13},
 eventdate = {2017-03-06/2017-03-10},
 publisher = {Gesellschaft f\"{u}r Informatik e.V.},
 year = {2017},
 doi = {10.18420/FIXME2017\textunderscore 01},
}
```

```
koppor@DESKTOP-KAK953S c:\git-repositories\gi\LNI-proceedings
$ sed -i 's/\\\\textunderscore /_/g' proceedings.bib

koppor@DESKTOP-KAK953S c:\git-repositories\gi\LNI-proceedings
$ cat proceedings.bib
@inproceedings{A1-1,
 author = {Vorname Nachname},
 title = {Erster eingeladener Vortrag},
 booktitle = {Conference Name (CN 2017)},
 pages = {13--13},
 eventdate = {2017-03-06/2017-03-10},
 publisher = {Gesellschaft f\"{u}r Informatik e.V.},
 year = {2017},
 doi = {10.18420/FIXME2017_01},
}
```

**Comment by koppor** [comment]
I fixed the issue with `_` in https://github.com/gi-ev/LNI-proceedings/pull/13
